<?php

class OrphanedTalkPagesHooks {
	/**
	 * Hook to add Special:OrphanedTalkPages to the list generated by QueryPage::getPages.
	 * Used by the maintenance script updateSpecialPages.
	 *
	 * @param array &$wgQueryPages
	 * @return bool
	 */
	public static function onwgQueryPages( array &$wgQueryPages ) {
		$wgQueryPages[] = [ 'SpecialOrphanedTalkPages', 'OrphanedTalkPages' ];

		return true;
	}
}
